Repository hacf-fr/sfrbox-api, pull requests merged in 2024-01, with the labels that each got.

#239 Add WLAN enablement controls
  src/sfrbox_api/bridge.py
  tests/test_bridge.py
Labels: enhancement

#226 Add 901 to know authentication failures
  src/sfrbox_api/bridge.py
Labels: bug

#243 Bump actions/{upload/download}-artifact from v3 to v4
  .github/workflows/tests.yml
Labels: dependencies, github_actions
